---
- hosts: testrepo
  tasks:
  - name: Change hostname 
    replace:
        path: /etc/hostname
        regexp: 'testrepo'
        replace: 'localrepo'
        backup: yes
  - name: Restart hostnamed service
    systemd:
        state: restarted
        name: systemd-hostnamed
  - name: Change IP address configuration file
    replace:
        path: /etc/sysconfig/network-scripts/ifcfg-ens192
        regexp: 'IPADDR=[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*'
        replace: 'IPADDR=10.4.160.43'
        backup: yes 
  - name: Reboot server
    command: reboot
